# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Basys-3-Master.xdc

# Block Designs: bd/mblaze_Autonomous_Car_SoC/mblaze_Autonomous_Car_SoC.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_clk_wiz_0_0/mblaze_Autonomous_Car_SoC_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_clk_wiz_0_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_clk_wiz_0_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_microblaze_0_0/mblaze_Autonomous_Car_SoC_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_microblaze_0_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_microblaze_0_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_dlmb_v10_0/mblaze_Autonomous_Car_SoC_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_dlmb_v10_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_dlmb_v10_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_ilmb_v10_0/mblaze_Autonomous_Car_SoC_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_ilmb_v10_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_ilmb_v10_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_dlmb_bram_if_cntlr_0/mblaze_Autonomous_Car_SoC_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_ilmb_bram_if_cntlr_0/mblaze_Autonomous_Car_SoC_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_lmb_bram_0/mblaze_Autonomous_Car_SoC_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_lmb_bram_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_lmb_bram_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_xbar_0/mblaze_Autonomous_Car_SoC_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_xbar_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_xbar_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_microblaze_0_axi_periph_0/mblaze_Autonomous_Car_SoC_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_microblaze_0_axi_intc_0/mblaze_Autonomous_Car_SoC_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_microblaze_0_xlconcat_0/mblaze_Autonomous_Car_SoC_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_mdm_1_0/mblaze_Autonomous_Car_SoC_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_mdm_1_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_mdm_1_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_rst_clk_wiz_0_100M_0/mblaze_Autonomous_Car_SoC_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_myip_Car_PWM_0_0/mblaze_Autonomous_Car_SoC_myip_Car_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_myip_Car_PWM_0_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_myip_Car_PWM_0_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_myip_Car_UltraSonic_0_0/mblaze_Autonomous_Car_SoC_myip_Car_UltraSonic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_myip_Car_UltraSonic_0_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_myip_Car_UltraSonic_0_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_myip_Car_Light_cntr_0_0/mblaze_Autonomous_Car_SoC_myip_Car_Light_cntr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_myip_Car_Light_cntr_0_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_myip_Car_Light_cntr_0_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_myip_Car_FND_0_0/mblaze_Autonomous_Car_SoC_myip_Car_FND_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_myip_Car_FND_0_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_myip_Car_FND_0_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_myip_Car_direction_w_0_0/mblaze_Autonomous_Car_SoC_myip_Car_direction_w_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_myip_Car_direction_w_0_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_myip_Car_direction_w_0_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_axi_gpio_0_0/mblaze_Autonomous_Car_SoC_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_axi_gpio_0_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_axi_gpio_0_1/mblaze_Autonomous_Car_SoC_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_axi_gpio_0_1 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_axi_gpio_0_1} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_axi_uartlite_0_0/mblaze_Autonomous_Car_SoC_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_axi_uartlite_0_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_axi_iic_0_0/mblaze_Autonomous_Car_SoC_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_axi_iic_0_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_axi_iic_0_0} -quiet] -quiet

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_clk_wiz_0_0/mblaze_Autonomous_Car_SoC_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_clk_wiz_0_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_clk_wiz_0_0/mblaze_Autonomous_Car_SoC_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_clk_wiz_0_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_clk_wiz_0_0/mblaze_Autonomous_Car_SoC_clk_wiz_0_0_ooc.xdc

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_microblaze_0_0/mblaze_Autonomous_Car_SoC_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_microblaze_0_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_microblaze_0_0/mblaze_Autonomous_Car_SoC_microblaze_0_0_ooc_debug.xdc

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_dlmb_v10_0/mblaze_Autonomous_Car_SoC_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_dlmb_v10_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_dlmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_ilmb_v10_0/mblaze_Autonomous_Car_SoC_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_ilmb_v10_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_ilmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_lmb_bram_0/mblaze_Autonomous_Car_SoC_lmb_bram_0_ooc.xdc

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_microblaze_0_axi_intc_0/mblaze_Autonomous_Car_SoC_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_microblaze_0_axi_intc_0/mblaze_Autonomous_Car_SoC_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_microblaze_0_axi_intc_0/mblaze_Autonomous_Car_SoC_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_mdm_1_0/mblaze_Autonomous_Car_SoC_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_mdm_1_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_mdm_1_0/mblaze_Autonomous_Car_SoC_mdm_1_0_ooc_trace.xdc

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_rst_clk_wiz_0_100M_0/mblaze_Autonomous_Car_SoC_rst_clk_wiz_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_rst_clk_wiz_0_100M_0/mblaze_Autonomous_Car_SoC_rst_clk_wiz_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_axi_gpio_0_0/mblaze_Autonomous_Car_SoC_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_axi_gpio_0_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_axi_gpio_0_0/mblaze_Autonomous_Car_SoC_axi_gpio_0_0_ooc.xdc

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_axi_gpio_0_0/mblaze_Autonomous_Car_SoC_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_axi_gpio_0_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_axi_gpio_0_1/mblaze_Autonomous_Car_SoC_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_axi_gpio_0_1 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_axi_gpio_0_1/mblaze_Autonomous_Car_SoC_axi_gpio_0_1_ooc.xdc

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_axi_gpio_0_1/mblaze_Autonomous_Car_SoC_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_axi_gpio_0_1 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_axi_uartlite_0_0/mblaze_Autonomous_Car_SoC_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_axi_uartlite_0_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_axi_uartlite_0_0/mblaze_Autonomous_Car_SoC_axi_uartlite_0_0_ooc.xdc

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_axi_uartlite_0_0/mblaze_Autonomous_Car_SoC_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_axi_uartlite_0_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_axi_iic_0_0/mblaze_Autonomous_Car_SoC_axi_iic_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_Autonomous_Car_SoC_axi_iic_0_0 || ORIG_REF_NAME==mblaze_Autonomous_Car_SoC_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mblaze_Autonomous_Car_SoC/ip/mblaze_Autonomous_Car_SoC_axi_iic_0_0/mblaze_Autonomous_Car_SoC_axi_iic_0_0_ooc.xdc

# XDC: bd/mblaze_Autonomous_Car_SoC/mblaze_Autonomous_Car_SoC_ooc.xdc
