# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/RTL_Autonomous_Car_Basys3/RTL_Autonomous_Car_Basys3.cache/wt [current_project]
set_property parent.project_path F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/RTL_Autonomous_Car_Basys3/RTL_Autonomous_Car_Basys3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/RTL_Autonomous_Car_Basys3/RTL_Autonomous_Car_Basys3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/imports/cora_z7/cora_z7_07s_exam/cora_z7_07s_exam.srcs/sources_1/new/Clock_Library_.v
  F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/imports/cora_z7/cora_z7_07s_exam/cora_z7_07s_exam.srcs/sources_1/new/FND_4digit_cntr.v
  F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/imports/cora_z7/cora_z7_07s_exam/cora_z7_07s_exam.srcs/sources_1/new/PWM_100x.v
  F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/imports/cora_z7/cora_z7_07s_exam/cora_z7_07s_exam.srcs/sources_1/new/UltraSonic_Profsr.v
  F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/imports/cora_z7/cora_z7_07s_exam/cora_z7_07s_exam.srcs/sources_1/new/exam01_combinational_Logic.v
  F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/imports/cora_z7/cora_z7_07s_exam/cora_z7_07s_exam.srcs/sources_1/new/exam02_sequential_logic.v
  F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/RTL_Autonomous_Car_Basys3/RTL_Autonomous_Car_Basys3.srcs/sources_1/imports/new/fan_bluetooth_top.v
  F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/RTL_Autonomous_Car_Basys3/RTL_Autonomous_Car_Basys3.srcs/sources_1/new/Autonomous_Car_Top.v
}
read_ip -quiet F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/RTL_Autonomous_Car_Basys3/RTL_Autonomous_Car_Basys3.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/RTL_Autonomous_Car_Basys3/RTL_Autonomous_Car_Basys3.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/RTL_Autonomous_Car_Basys3/RTL_Autonomous_Car_Basys3.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/constrs_1/imports/digilent-xdc-master/Basys-3-Master.xdc
set_property used_in_implementation false [get_files F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/constrs_1/imports/digilent-xdc-master/Basys-3-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Autonomous_Car_Top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Autonomous_Car_Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Autonomous_Car_Top_utilization_synth.rpt -pb Autonomous_Car_Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
